linters:
  Rubocop:
    enabled: true
    rubocop_config:
      inherit_from:
        - '.rubocop.yml'
      Layout/InitialIndentation:
        Enabled: false
      Layout/LineLength:
        Max: 110
      Layout/TrailingEmptyLines:
        Enabled: false
      Lint/UselessAssignment:
        Enabled: false
