default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  host: localhost
  password:
  database: alterf

development:
  <<: *default
  username: development

test:
  <<: *default
  username: test
  database: alterf_test

production:
  <<: *default
  username: production
